"""new fields in user model

Revision ID: 872b02fa8981
Revises: c484d1a6ec04
Create Date: 2025-02-02 17:44:23.737564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '872b02fa8981'
down_revision = 'c484d1a6ec04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
