"""Add avatar column to user table

Revision ID: 96e2e30f3123
Revises: 2322a096f4d0
Create Date: 2025-02-07 18:15:59.832505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96e2e30f3123'
down_revision = '2322a096f4d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('body',
               existing_type=sa.VARCHAR(length=140),
               type_=sa.String(length=10000),
               existing_nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        op.add_column('user', sa.Column('avatar', sa.String(length=140), nullable=False, server_default="1"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('avatar')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('body',
               existing_type=sa.String(length=10000),
               type_=sa.VARCHAR(length=140),
               existing_nullable=False)

    # ### end Alembic commands ###
