"""Add avatar column to user table

Revision ID: a9aaba620bae
Revises: cc36dcaa99e7
Create Date: 2025-02-08 20:33:36.493059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9aaba620bae'
down_revision = 'cc36dcaa99e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rank', sa.String(length=120), nullable=False, server_default="1"))
        batch_op.alter_column('avatar',
               existing_type=sa.VARCHAR(length=140),
               type_=sa.String(length=3),
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('avatar',
               existing_type=sa.String(length=3),
               type_=sa.VARCHAR(length=140),
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
        batch_op.drop_column('rank')

    # ### end Alembic commands ###
