"""Recreate migration

Revision ID: cc36dcaa99e7
Revises: fb1884e487a4
Create Date: 2025-02-07 18:40:58.066222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc36dcaa99e7'
down_revision = 'fb1884e487a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar', sa.String(length=140), nullable=False, server_default="1"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar')
    # ### end Alembic commands ###
